routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/', function () {
    return view('welcome');
})->middleware('auth');
Route::group(['prefix' => '', 'middleware' => 'auth'], function() {
Route::resource('/Direction','Directions\DirectionsController');
Route::resource('/DirectionT','DirectionsT\DirectionsTController');
Route::resource('/Departement','Departements\DepartementsController');
Route::resource('/Office','Offices\OfficesController');
Route::resource('/Fonction','Fonctions\FonctionsController');
Route::resource('/Courrier','Courriers\CourriersController');
Route::resource('/Type','Types\TypesController');
Route::resource('/Nature','Natures\NaturesController');
Route::resource('/Etat','Etats\EtatsController');
Route::resource('/Priorite','Priorites\PrioritesController');
Route::resource('/Chrono','Chronos\ChronosController');
Route::resource('/ChronosArchivage','ChronosArchive\ChronosArchiveController');
Route::resource('/Role','Roles\RolesController');
Route::resource('/Affectation','Affectations\AffectationsController');
Route::resource('/Redirection','Redirection\RedirectionController');
Route::resource('/Archivage','Archivages\ArchivagesController');


Route::resource('/Reponse','Reponse\ReponseController');
Route::get('/pdf/{order}', ['as' => 'order.pdf', 'uses' => 'ReponseController@reponsePdf']);
Route::get('/archive/{id}', 'Courriers\CourriersController@archive')->name('archive');
Route::delete('/supprimecourrier/{id}', 'Courriers\CourriersController@supprimecourrier')->name('Courrier.destroy1');

Route::post('/supprimecourrier2/{id}', 'Courriers\CourriersController@supprimecourrier')->name('Courrier.destroy2');

Route::get('/home', 'HomeController@index')->name('home');
});
Route::get('/getresetpassword','Users\UsersController@getresetpassword')->name('getresetpassword');
Route::post('/postresetpassword','Users\UsersController@postresetpassword')->name('postresetpassword');
Route::resource('/User','Users\UsersController');
Auth::routes();
Route::get('/Close/{affect_id}/{etat_id}/{courrier_id}', 'Courriers\CourriersController@close')->name('close');

Route::get('/profile/{id}','Users\UsersController@show');
Route::get('/deconnexion','Users\UsersController@deconnexion');

Route::get('/statut/{id}', 'Users\UsersController@statut')->name('statut');
Route::get('/archivedef/{numero}', 'Archivages\ArchivagesController@archivedef')->name('archivedef');
Route::get('/delete/{id}', 'Archivages\ArchivagesController@delete')->name('delete');
Route::get('/remettre/{id}', 'Archivages\ArchivagesController@remettre')->name('remettre');

app/Http/Controllers/Roles/RolesController.php
<?php

namespace App\Http\Controllers\Roles;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Roles;
use App\Model\Users;
use Illuminate\Support\Facades\Validator;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
    {
        $this->middleware('auth');
    }

    
    public function index()
    {
       $roles = Roles::get();
       return view('role.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
        'libelle' => ['required', 'string', 'max:255', 'unique:roles']
        ]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $libelle = $request->libelle;
        $abrev = $request->abrev;
        $this->validator($request->all())->validate();
        Roles::create(['libelle' => $libelle, 'abrev'=>$abrev]);
        flashy()->success('Action traitée avec succes.', '');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $roles = Roles::get();
        return view('role.index', compact('roles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Roles::where('id', $id)->get();
        return view('role.edit', compact('roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $libelle = $request->libelle;
        $abrev   = $request->abrev;
        Roles::where('id', $id)->update(['libelle' => $libelle, 'abrev'=>$abrev]);
        flashy()->success('Action traitée avec succes.', '');
        return redirect()->route('Role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $users = Users::where('role_id',$id)->get()->count();
        if ($users < 1) {
            Roles::where('id', $id)->delete();
            flashy()->success('Action traitée avec succes.', '');
        }else{
            flashy()->error('Erreur de suppression.Ce rôle est associé à des agents.', '');
        }
        return redirect()->route('Role.index');
    }
}

resources/views/role/edit.blade.php
@extends('layouts.app1')
@section('main')
<br><br>
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Modifier le rôle</a></li>                 
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
                @foreach($roles as $role)
                <form class="form-horizontal" method="POST" action="{{ route('Role.update', $role->id) }}">
                       @csrf
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Nom</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('libelle') is-invalid @enderror" id="libelle" placeholder="Nom" name="libelle" value="{{ $role->libelle }}" required autocomplete="libelle" autofocus>
                        </div>
                         @error('libelle')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                         @enderror
                      </div>                      
                      <div class="form-group row">
                        <label for="inputName2" class="col-sm-2 col-form-label">Abréviation</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('abrev') is-invalid @enderror" id="inputName2" placeholder="" name="abrev" value="{{$role->abrev }}" required autocomplete="abrev" autofocus>
                        </div>
                         @error('abrev')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                          @enderror
                      </div>                     
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">Modifer</button>
                        </div>
                      </div>
                     {{ method_field('PUT') }}
                    </form>
                    @endforeach
                  </div>
               
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.app1')
@section('main')
<br><br>
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Liste</a></li>
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ajouter un rôle</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
               <div class="table-responsive">
                 <table id="example1" class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Nom</th>
                      <th>Abréviation</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Nom</th>  
                      <th>Abréviation</th>
                      <th>Actions</th>                   
                    </tr>
                  </tfoot>
                  <tbody>
                     
                    @foreach($roles as $role)
                    <tr>
                      <td> {{ $role->libelle }}</td>
                      <td> {{ $role->abrev }}</td>
                      <td><div class="btn-group">
                          <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Options
                          </button>
                          <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{ route('Role.edit', $role->id) }}">Modifier</a> 
                           <form method="POST" action="{{ route('Role.destroy', $role->id) }}">
                             @csrf
                             {{ method_field('DELETE') }}
                            <button  class="dropdown-item" >Supprimer
                           </button>
                          </form></div></div></td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
                  </div>
                  <!-- /.tab-pane -->

                 <div class="tab-pane" id="settings">
                    <form class="form-horizontal" method="POST" action="{{ route('Role.store') }}">
                       @csrf
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Nom</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('libelle') is-invalid @enderror" id="libelle" placeholder="" name="libelle" value="{{ old('libelle') }}" required autocomplete="libelle" autofocus>
                        </div>
                         @error('libelle')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                         @enderror
                      </div>
                       <div class="form-group row">
                        <label for="inputName2" class="col-sm-2 col-form-label">Abréviation</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('abrev') is-invalid @enderror" id="inputName2" placeholder="facultatif" name="abrev" value="{{ old('abrev') }}"  autocomplete="abrev" autofocus>
                        </div>
                         @error('abrev')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                          @enderror
                      </div>                                                      
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">Ajouter</button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
@endsection