routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 
Route::get('/', function () {
    return view('welcome');
})->middleware('auth');
Route::group(['prefix' => '', 'middleware' => 'auth'], function() {
Route::resource('/Direction','Directions\DirectionsController');
Route::resource('/DirectionT','DirectionsT\DirectionsTController');
Route::resource('/Departement','Departements\DepartementsController');
Route::resource('/Office','Offices\OfficesController');
Route::resource('/Fonction','Fonctions\FonctionsController');
Route::resource('/Courrier','Courriers\CourriersController');
Route::resource('/Type','Types\TypesController');
Route::resource('/Nature','Natures\NaturesController');
Route::resource('/Etat','Etats\EtatsController');
Route::resource('/Priorite','Priorites\PrioritesController');
Route::resource('/Chrono','Chronos\ChronosController');
Route::resource('/ChronosArchivage','ChronosArchive\ChronosArchiveController');
Route::resource('/Role','Roles\RolesController');
Route::resource('/Affectation','Affectations\AffectationsController');
Route::resource('/Redirection','Redirection\RedirectionController');
Route::resource('/Archivage','Archivages\ArchivagesController');


Route::resource('/Reponse','Reponse\ReponseController');
Route::get('/pdf/{order}', ['as' => 'order.pdf', 'uses' => 'ReponseController@reponsePdf']);
Route::get('/archive/{id}', 'Courriers\CourriersController@archive')->name('archive');
Route::delete('/supprimecourrier/{id}', 'Courriers\CourriersController@supprimecourrier')->name('Courrier.destroy1');

Route::post('/supprimecourrier2/{id}', 'Courriers\CourriersController@supprimecourrier')->name('Courrier.destroy2');

Route::get('/home', 'HomeController@index')->name('home');
});
Route::get('/getresetpassword','Users\UsersController@getresetpassword')->name('getresetpassword');
Route::post('/postresetpassword','Users\UsersController@postresetpassword')->name('postresetpassword');
Route::resource('/User','Users\UsersController');
Auth::routes();
Route::get('/Close/{affect_id}/{etat_id}/{courrier_id}', 'Courriers\CourriersController@close')->name('close');

Route::get('/profile/{id}','Users\UsersController@show');
Route::get('/deconnexion','Users\UsersController@deconnexion');

Route::get('/statut/{id}', 'Users\UsersController@statut')->name('statut');
Route::get('/archivedef/{numero}', 'Archivages\ArchivagesController@archivedef')->name('archivedef');
Route::get('/delete/{id}', 'Archivages\ArchivagesController@delete')->name('delete');
Route::get('/remettre/{id}', 'Archivages\ArchivagesController@remettre')->name('remettre');

resources/views/chronoA/dossier.blade.php
@extends('layouts.app1')
@section('main')
@inject('typearchi', 'App\Helpers\Helpers')
@inject('courid', 'App\Helpers\Helpers')
<br><br>
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Contenu du dossier</a></li>
                  
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
               <div class="table-responsive">
                 <table id="example1" class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <td>Actions</td>
                      <th>Numero du courrier</th>
                      <th>Type d'archivage</th>
                     
                      <th>Date d'expiration</th>
                      <th>Note</th>

                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <td>Action</td>
                      <th>Numero</th>
                      <th>Type d'archivage</th>
                     
                      <th>Date d'expiration</th>
                      <th>Note</th>                 
                    </tr>
                  </tfoot>
                  <tbody>
                     
                    @foreach($courriers as $courrier)
                    <tr>
                     <td><div class="btn-group">
                          <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Options
                          </button>
                          <div class="dropdown-menu">
                             <a class="dropdown-item" href="{{ route('Courrier.show', $courid::courid($courrier->numero)) }}">Consulter</a> 
                           </form>                       
                           </div></div></td>
                      <td> {{ $courrier->numero }}</td>
                      <td>{{$typearchi::archi($courrier->typearchi)}}
                      </td>
                      
                        <td> {{ $courrier->datefinarchi }}</td>
                      <td> {{ $courrier->instructions }}</td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
                  </div>
                  <!-- /.tab-pane -->


                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
@endsection

resources/views/chronoA/edit.blade.php
@extends('layouts.app1')
@section('main')
<br><br>
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Modifier un dossier</a></li>                 
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
                @foreach($chronos as $chrono)
                <form class="form-horizontal" method="POST" action="{{ route('ChronosArchivage.update', $chrono->id) }}">
                       @csrf
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Libellé</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('libelle') is-invalid @enderror" id="libelle" placeholder="" name="libelle" value="{{ $chrono->libelle }}" required autocomplete="libelle" autofocus>
                        </div>
                         @error('libelle')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                         @enderror
                      </div>                      
                      <div class="form-group row">
                        <label for="inputName2" class="col-sm-2 col-form-label">Abréviations</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('abrev') is-invalid @enderror" id="inputName2" placeholder="Name" name="abrev" value="{{$chrono->abrev }}"  autocomplete="abrev" autofocus>
                        </div>
                         @error('abrev')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                          @enderror
                      </div>                     
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">Modifer le nom du dossier</button>
                        </div>
                      </div>
                     {{ method_field('PUT') }}
                    </form>
                    @endforeach
                  </div>
               
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
@endsection

resources/views/chronoA/index.blade.php
@extends('layouts.app1')
@section('main')
<br><br>
          <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
              <div class="card-header p-2">
                <ul class="nav nav-pills">
                  <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Liste des dossiers</a></li>
                  <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Créer un dossier</a></li>
                </ul>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content">

                  <!-- /.tab-pane -->
              <div class="active tab-pane" id="timeline">
               <div class="table-responsive">
                 <table id="example1" class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Libellé</th>
                      <th>Abréviations</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                      <th>Libellé</th>  
                      <th>Abréviations</th> 
                      <th>Actions</th>                  
                    </tr>
                  </tfoot>
                  <tbody>
                     
                    @foreach($chronos as $chrono)
                    <tr>
                      <td> {{ $chrono->libelle }}</td>
                      <td> {{ $chrono->abrev }}</td>
                      <td><div class="btn-group">
                          <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Options
                          </button>
                          <div class="dropdown-menu">
                           <a class="dropdown-item" href="{{ route('ChronosArchivage.edit', $chrono->id) }}">Modifier</a>
                           <a class="dropdown-item" href="{{ route('ChronosArchivage.show', $chrono->id) }}">Ouvrir ce dossier</a> 
                          </div></div></td>
                            
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
                  </div>
                  <!-- /.tab-pane -->

                 <div class="tab-pane" id="settings">
                    <form class="form-horizontal" method="POST" action="{{ route('ChronosArchivage.store') }}">
                       @csrf
                      <div class="form-group row">
                        <label for="inputName" class="col-sm-2 col-form-label">Libellé</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('libelle') is-invalid @enderror" id="libelle" placeholder="nom du dossier" name="libelle" value="{{ old('libelle') }}" required autocomplete="libelle" autofocus>
                        </div>
                         @error('libelle')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                         @enderror
                      </div>
                      <div class="form-group row">
                        <label for="inputName2" class="col-sm-2 col-form-label">Abréviation</label>
                        <div class="col-sm-10">
                          <input type="text" class="form-control @error('abrev') is-invalid @enderror" id="inputName2" placeholder="facultatif" name="abrev" value="{{ old('abrev') }}" autocomplete="abrev" autofocus>
                        </div>
                         @error('abrev')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                          @enderror
                      </div>                                                      
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-10">
                          <button type="submit" class="btn btn-primary">Ajouter</button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
@endsection